-- Create Sequences
CREATE SEQUENCE PRODUCT_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE RAW_MATERIAL_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE PRODUCT_MATERIAL_SEQ START WITH 1 INCREMENT BY 1;
-- Create Product Table
CREATE TABLE PRODUCT (
    ID NUMBER(19, 0) PRIMARY KEY,
    NAME VARCHAR2(255) NOT NULL,
    PRICE NUMBER(19, 2) NOT NULL
);
-- Create Raw Material Table
CREATE TABLE RAW_MATERIAL (
    ID NUMBER(19, 0) PRIMARY KEY,
    NAME VARCHAR2(255) NOT NULL,
    STOCK_QUANTITY NUMBER(19, 2) NOT NULL
);
-- Create Product Material Association Table
CREATE TABLE PRODUCT_MATERIAL (
    ID NUMBER(19, 0) PRIMARY KEY,
    PRODUCT_ID NUMBER(19, 0) NOT NULL,
    RAW_MATERIAL_ID NUMBER(19, 0) NOT NULL,
    REQUIRED_QUANTITY NUMBER(19, 2) NOT NULL,
    CONSTRAINT FK_PRODUCT FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(ID),
    CONSTRAINT FK_RAW_MATERIAL FOREIGN KEY (RAW_MATERIAL_ID) REFERENCES RAW_MATERIAL(ID)
);